version: "3.8" # Versi칩n del compose file

# Servicios que componen nuestra aplicaci칩n.
## Un servicio puede estar compuesto por uno o m치s contenedores.
services:
# nombre del servicio.
  app:
    build: .
    # Declaraci칩n de variables de entorno.
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    # Indica que este servicio depende de otro, en este caso DB. El servicio app solo iniciara si el servicio db inicia correctamente.
    depends_on:
      - db
    # Puerto del contenedor expuesto.
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      # indica que ficheros debe ignorar
      - /usr/src/node_modules
    command: npx nodemon index.js

  db:
    image: mongo
