version: "3.8" # Versi칩n del compose file

# Servicios que componen nuestra aplicaci칩n.
## Un servicio puede estar compuesto por uno o m치s contenedores.
services:
# nombre del servicio.
  app:
    image: platziapp
    # Declaraci칩n de variables de entorno.
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    # Indica que este servicio depende de otro, en este caso DB. El servicio app solo iniciara si el servicio db inicia correctamente.
    depends_on:
      - db
    # Puerto del contenedor expuesto.
    ports:
      - "3000-3001:3000" # Esto es para que al escalar el servicio "app" en dos instancias. 
      # Ambas apunten al puerto 3000 de sus contenedores y lo expongan en el 3000 y 3001 local

  db:
    image: mongo
